# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a8a6a68a7b085acb32e37ecd1f5b31c144bb39a2441f6956dd78a516cf6936c1ca692e1dde0f9e478ccec3b46ff4f925fbe82f26d31bac7697b5a06d62b5bf

test:
  secret_key_base: d96735ff3a15d61dde0a546ba4b4bbaa45160ce5d8b4143026445dbce076f26e217e7c9d59bb02f820be4d4d66d45efaef67622a557c6b348eea03e16461b6e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
